### ISSUE TITLE
1.0.3 crashes with forbidden and arcanus

### ISSUE THREAD

**Issue by katubug** [bigenergy/achievement-optimizer#10]
When I update to version 1.0.3 for forge 1.20.1, I get this screen: https://i.imgur.com/o0nSmAD.png

Here is my latest.log: https://gist.github.com/katubug/3a754868a56cb645ce75c6b3193bedd7

And my crash report: [crash-2024-05-20_16.46.53-fml.txt](https://github.com/bigenergy/achievement-optimizer/files/15382042/crash-2024-05-20_16.46.53-fml.txt)

**Comment by bigenergy** [comment]
duplicate https://github.com/bigenergy/achievement-optimizer/issues/8
