### ISSUE TITLE
Crash on Main menu when mod is active. 

### ISSUE THREAD

**Issue by Zelioth** [bigenergy/achievement-optimizer#12]
[crash-2024-05-22_02.59.10-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15399971/crash-2024-05-22_02.59.10-client.txt)

Minecraft 1.20.1
Forge 47.2.32
AO 1.0.3

**Comment by bigenergy** [comment]
duplicate https://github.com/bigenergy/achievement-optimizer/issues/8
