### ISSUE TITLE
Game Crashes on 1.21 NeoForge

### ISSUE THREAD

**Issue by ModernGamingWorld** [bigenergy/achievement-optimizer#13]
**Describe the bug**
![2024-06-21_21 47 03](https://github.com/bigenergy/achievement-optimizer/assets/75923060/bc2f8ac9-3034-4f42-9a61-236ead8ebdd2)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**\
 - Mod Version [AchievementOptimizer-1.21.0-1.1.0-neo]
 - NeoForge Version [21.0.21]

**Additional context**
Add any other context about the problem here, crash report and logs.

**Comment by bigenergy** [comment]
oops, sorry. 
fixed in v.1.1.0.1

thanks for report!
