### ISSUE TITLE
Info for config adjustment

### ISSUE THREAD

**Issue by VinceKezel** [bigenergy/achievement-optimizer#14]
I understand the concept and appreciate the CPU cycles saved by checking achievement requirements less often.

But I don't understand the skip tick setting.

In the config it's `skipTicksAdvancements = 5` by default. That seems to delay the toast notification about an achievement in our multiplayer world by about 5 minutes. I set it to 2 with no change. Are the ticks skipped in the same scale as 20 ticks per second in the game?

**Comment by bigenergy** [comment]
hi, please use issue template (https://github.com/bigenergy/achievement-optimizer/issues/new/choose)

**Comment by VinceKezel** [comment]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
answer to my question as stated above

**Describe alternatives you've considered**
considered asking a question as stated above

**Additional context**
see question stated above

**Comment by bigenergy** [comment]
send me the versions and what mod loader you use, also send me the Minecraft version.  Another question, do you have several mods or some kind of modpack?

**Comment by VinceKezel** [comment]
I'm curious about how the config works and how the tick skipping math is... 
I do appreciate every bit of optimization for a smooth game play experience for the family server, so I am grateful you created this mod.

After changing the config does it take affect immediately or do I need to restart server?

MC 1.20.1
FML 47.3.0
Achievement Optimizer-1.20.1-1.0.5
120+ mods

**Comment by bigenergy** [comment]
> After changing the config does it take affect immediately or do I need to restart server?

In theory, changes occur without rebooting the server.



> I do appreciate every bit of optimization for a smooth game play experience for the family server, so I am grateful you created this mod.

The ticks of the achievement check call event are skipped, unfortunately I can't answer exactly how many times this method is called in vanilla.
If you have a small server up to 5 players, optimization makes almost no sense, you can set 0 in the config.
