### ISSUE TITLE
Update to 1.21.1

### ISSUE THREAD

**Issue by Fantomrat** [bigenergy/achievement-optimizer#16]
**Is your feature request related to a problem? Please describe.**
mod does not exist for 1.21.1
mod for 1.21 does not work with 1.21.1

**Describe the solution you'd like**
Update to 1.21.1

**Describe alternatives you've considered**
-

**Additional context**
I've only tested fabric version
- Replace mod 'AchievementOptimizer' (achiopt) 1.21-1.1.0 with any version that is compatible with:
		 - minecraft 1.21.1

**Comment by bigenergy** [comment]
thx for report, mod updated
