### ISSUE TITLE
Not A "Performance" Mod

### ISSUE THREAD

**Issue by Nyxane** [bigenergy/achievement-optimizer#19]
InventoryChange event only gets emitted if the inventory changes when it changes, not every tick, forcing players to trigger the inventory change 5 times to register any advancements, this all feels AI made.

**Comment by bigenergy** [comment]
I don't force you to use it, if you don't like it, delete it.

**Comment by 62832** [comment]
He's not saying he doesn't like it, he's saying that your mod objectively sucks. Which it does.
