### ISSUE TITLE
[1.20.1] Crash. Mixin error on launching game.

### ISSUE THREAD

**Issue by Gbergz** [bigenergy/achievement-optimizer#2]
Title^

("com.bigenergy.achiopt.mixins.CompoundTagMixin' was not found")

Mod version: 1.0 | https://www.curseforge.com/minecraft/mc-mods/achievements-optimizer/files/4752544
Forge: 47.1.3

Report: https://gist.github.com/Gbergz/8f0f332797d95c75f8ffd25b343d42f4

**Comment by Daltaxy** [comment]
same thing in my case
https://paste.essential.gg/6WtS13nA9g

**Comment by bigenergy** [comment]
thanks for the report, I uploaded the new version 1.0.1 for 1.20.1 on curseforge
