### ISSUE TITLE
1.19.2 - Compatibility issue with ``Kingdom Keys 2`` 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [bigenergy/achievement-optimizer#3]
https://github.com/Wehavecookies56/Kingdom-Keys/issues/39

I have not tested every detail of my modpack so here is my workspace. Happy bug hunting.

https://www.dropbox.com/scl/fo/wmsofktyunm5edr8ouy83/h?rlkey=qbk00ya7hbxto6ae2mg6jwcee&dl=0

**Comment by bigenergy** [comment]
Send me the error logs.

**Comment by P3rf3ctXZer0** [comment]
I guess they said it was on their end. Thanks for the headsup.
