### ISSUE TITLE
Will there be a possibility of porting to a lower version?

### ISSUE THREAD

**Issue by ALONEJINGYAN** [bigenergy/achievement-optimizer#5]
Just a suggestion, e.g. for 1.16.5 :)

**Comment by bigenergy** [comment]
Thanks for the suggestion, version for 1.16.5 coming soon

**Comment by bigenergy** [comment]
@ALONEJINGYAN pls test https://legacy.curseforge.com/minecraft/mc-mods/achievements-optimizer/files/4866775
