### ISSUE TITLE
Could this mod be published on Modrinth?

### ISSUE THREAD

**Issue by Jerome226** [bigenergy/achievement-optimizer#6]
I have multiples reasons I think it could benefits both users and you:
- Modrinth is for what I know, a pretty good platform
- Modrinth has it's own client and lot of people use it instead of curse, so posting it there, would allow other players to be able to use your mod.
- Extra points and revenues for you
- More people can enjoy the mod

(I'm not sponsored by them, It's just that because of some mods like you're not being avalaible on modrinth, it makes pack making harder, because you can only use modrinth mods on modrinth packs)

**Comment by bigenergy** [comment]
Thanks for the suggestion, I'll add this mod to Modrinth. Soon.

**Comment by bigenergy** [comment]
The mod is still being moderated.

**Comment by bigenergy** [comment]
https://modrinth.com/mod/achievements-optimizer
