### ISSUE TITLE
Would this mod conflict with Icterine?

### ISSUE THREAD

**Issue by StormDragon-64** [bigenergy/achievement-optimizer#7]
I'm wondering if using both at the same time would get me even better performance, or if they conflict with each other because they do similar things, causing them to be incompatible.
[Here's the link to Icterine](https://modrinth.com/mod/icterine) if you don't know what I'm talking about.

**Comment by StormDragon-64** [comment]
If I can't ask questions here, where am I supposed to ask questions?

**Comment by bigenergy** [comment]
> If I can't ask questions here, where am I supposed to ask questions?

I closed the issue, but my response was not sent.
At first glance, Icterine does almost the same thing as my mod. They won't work together.
