### ISSUE TITLE
when updating to 1.0.3, it becomes incompatible with better nether?

### ISSUE THREAD

**Issue by KingOfStrangeness69** [bigenergy/achievement-optimizer#8]
basically what the title says, when i update the mod and try and boot the game, it crashes and mentions better nether?

**Comment by bigenergy** [comment]
Send something, such as launch logs and a crash report.

**Comment by KingOfStrangeness69** [comment]
[latest.log](https://github.com/bigenergy/achievement-optimizer/files/15377636/latest.log)
[crash-2024-05-20_15.31.50-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15377638/crash-2024-05-20_15.31.50-client.txt)


> Send something, such as launch logs and a crash report.

**Comment by maximogta** [comment]
Same issue here. Crashes with 1.0.3
[crash-2024-05-20_17.36.09-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15378911/crash-2024-05-20_17.36.09-client.txt)
[latest.log](https://github.com/bigenergy/achievement-optimizer/files/15378923/latest.log)

**Comment by DeshiDesu** [comment]
Im getting the same error:
`[Render thread/FATAL] Mixin apply for mod achiopt failed achiopt.mixins.json:ItemPredicateMixin from mod achiopt -> net.minecraft.advancements.critereon.ItemPredicate: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onMatches could not find any targets matching 'matches' in net.minecraft.advancements.critereon.ItemPredicate. No refMap loaded. [PREINJECT Applicator Phase -> achiopt.mixins.json:ItemPredicateMixin from mod achiopt -> Prepare Injections ->  -> handler$ebd000$achiopt$onMatches(Lnet/minecraft/world/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]`

[crash-2024-05-20_14.45.20-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15380797/crash-2024-05-20_14.45.20-client.txt)

**Comment by bigenergy** [comment]
> [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15377636/latest.log) [crash-2024-05-20_15.31.50-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15377638/crash-2024-05-20_15.31.50-client.txt)
> 
> > Send something, such as launch logs and a crash report.

Which version are you using? And what mod loader do you have?

**Comment by KingOfStrangeness69** [comment]
> > [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15377636/latest.log) [crash-2024-05-20_15.31.50-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15377638/crash-2024-05-20_15.31.50-client.txt)
> > > Send something, such as launch logs and a crash report.
> 
> Which version are you using? And what mod loader do you have?

the newest update when it crashes. curseforge

**Comment by bigenergy** [comment]
Please write in detail, indicating all versions and mod loaders.

**Comment by DeshiDesu** [comment]
> Please write in detail, indicating all versions and mod loaders.

In my case:
### MC 1.20.1
### Forge 47.2.32

**Mods:**

- AchievementOptimizer-1.20.1-1.0.3.jar
- Connector-1.0.0-beta.43+1.20.1.jar
- fabric-api-0.92.1+1.11.8+1.20.1.jar
- bclib-3.0.14.jar
- better-nether-9.0.10.jar

**Console Log:**
[latest.log](https://github.com/bigenergy/achievement-optimizer/files/15395750/latest.log)

**Crash Log:**
[crash-2024-05-21_17.48.49-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15395735/crash-2024-05-21_17.48.49-client.txt)

**Video:**
https://github.com/bigenergy/achievement-optimizer/assets/120287925/0f6474b4-cd54-415c-b828-45adad4eb1e2

I hope this amount of information is sufficient

**Comment by Groupix05** [comment]
Same issue here, And for the mod list it's not fabric api, it's Forgified Fabric API

**Comment by bigenergy** [comment]
> > Please write in detail, indicating all versions and mod loaders.
> 
> In my case:
> 
> ### MC 1.20.1
> ### Forge 47.2.32
> **Mods:**
> 
> * AchievementOptimizer-1.20.1-1.0.3.jar
> * Connector-1.0.0-beta.43+1.20.1.jar
> * fabric-api-0.92.1+1.11.8+1.20.1.jar
> * bclib-3.0.14.jar
> * better-nether-9.0.10.jar
> 
> **Console Log:** [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15395750/latest.log)
> 
> **Crash Log:** [crash-2024-05-21_17.48.49-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15395735/crash-2024-05-21_17.48.49-client.txt)
> 
> **Video:** https://github.com/bigenergy/achievement-optimizer/assets/120287925/0f6474b4-cd54-415c-b828-45adad4eb1e2
> 
> I hope this amount of information is sufficient

why are you using fabric in forge?

**Comment by DeshiDesu** [comment]
> > > Please write in detail, indicating all versions and mod loaders.
> > 
> > 
> > In my case:
> > ### MC 1.20.1
> > ### Forge 47.2.32
> > **Mods:**
> > 
> > * AchievementOptimizer-1.20.1-1.0.3.jar
> > * Connector-1.0.0-beta.43+1.20.1.jar
> > * fabric-api-0.92.1+1.11.8+1.20.1.jar
> > * bclib-3.0.14.jar
> > * better-nether-9.0.10.jar
> > 
> > **Console Log:** [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15395750/latest.log)
> > **Crash Log:** [crash-2024-05-21_17.48.49-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15395735/crash-2024-05-21_17.48.49-client.txt)
> > **Video:** https://github.com/bigenergy/achievement-optimizer/assets/120287925/0f6474b4-cd54-415c-b828-45adad4eb1e2
> > I hope this amount of information is sufficient
> 
> why are you using fabric in forge?

I'll assume you dont know what Connecter Sinytra is so let me give a quick overview. Its a well known mod in the community that allows you to use fabric mods on the forge modloader. Its also very useful in modding without having to exclude any great mods like betternether due to limitations of different modloaders.

Btw, just as the issue's title indicates, the previous version 1.0.2 worked great with betternether but not for 1.0.3. So something along the update could have broke compatibility, but we wouldn't know until you point that out for us which is why we want your help. 😊

**Comment by bigenergy** [comment]
@DeshiDesu pls check new version
[AchievementOptimizer-1.20.1-1.0.4.zip](https://github.com/bigenergy/achievement-optimizer/files/15400011/AchievementOptimizer-1.20.1-1.0.4.zip)

**Comment by DeshiDesu** [comment]
> @DeshiDesu pls check new version [AchievementOptimizer-1.20.1-1.0.4.zip](https://github.com/bigenergy/achievement-optimizer/files/15400011/AchievementOptimizer-1.20.1-1.0.4.zip)

It sadly did not work:
[crash-2024-05-22_04.11.17-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400137/crash-2024-05-22_04.11.17-client.txt)
[latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400219/latest.log)


If you think the cause is not from your mod maybe try contacting with the guys from sinytra connector?

**Comment by bigenergy** [comment]
> > @DeshiDesu pls check new version [AchievementOptimizer-1.20.1-1.0.4.zip](https://github.com/bigenergy/achievement-optimizer/files/15400011/AchievementOptimizer-1.20.1-1.0.4.zip)
> 
> It sadly did not work: [crash-2024-05-22_04.11.17-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400137/crash-2024-05-22_04.11.17-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400219/latest.log)
> 
> If you think the cause is not from your mod maybe try contacting with the guys from sinytra connector?

thx, judging by the errors, this version should work
[AchievementOptimizer-1.20.1-1.0.4.1.zip](https://github.com/bigenergy/achievement-optimizer/files/15400255/AchievementOptimizer-1.20.1-1.0.4.1.zip)

**Comment by DeshiDesu** [comment]
> > > @DeshiDesu pls check new version [AchievementOptimizer-1.20.1-1.0.4.zip](https://github.com/bigenergy/achievement-optimizer/files/15400011/AchievementOptimizer-1.20.1-1.0.4.zip)
> > 
> > 
> > It sadly did not work: [crash-2024-05-22_04.11.17-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400137/crash-2024-05-22_04.11.17-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400219/latest.log)
> > If you think the cause is not from your mod maybe try contacting with the guys from sinytra connector?
> 
> thx, judging by the errors, this version should work [AchievementOptimizer-1.20.1-1.0.4.1.zip](https://github.com/bigenergy/achievement-optimizer/files/15400255/AchievementOptimizer-1.20.1-1.0.4.1.zip)

Did not work again
[crash-2024-05-22_04.21.25-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400296/crash-2024-05-22_04.21.25-client.txt)
[latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400299/latest.log)

**Comment by bigenergy** [comment]
> > > > @DeshiDesu pls check new version [AchievementOptimizer-1.20.1-1.0.4.zip](https://github.com/bigenergy/achievement-optimizer/files/15400011/AchievementOptimizer-1.20.1-1.0.4.zip)
> > > 
> > > 
> > > It sadly did not work: [crash-2024-05-22_04.11.17-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400137/crash-2024-05-22_04.11.17-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400219/latest.log)
> > > If you think the cause is not from your mod maybe try contacting with the guys from sinytra connector?
> > 
> > 
> > thx, judging by the errors, this version should work [AchievementOptimizer-1.20.1-1.0.4.1.zip](https://github.com/bigenergy/achievement-optimizer/files/15400255/AchievementOptimizer-1.20.1-1.0.4.1.zip)
> 
> Did not work again [crash-2024-05-22_04.21.25-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400296/crash-2024-05-22_04.21.25-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400299/latest.log)

okay, maybe this version)
[AchievementOptimizer-1.20.1-1.0.4.2.zip](https://github.com/bigenergy/achievement-optimizer/files/15400436/AchievementOptimizer-1.20.1-1.0.4.2.zip)

**Comment by DeshiDesu** [comment]
> > > > > @DeshiDesu pls check new version [AchievementOptimizer-1.20.1-1.0.4.zip](https://github.com/bigenergy/achievement-optimizer/files/15400011/AchievementOptimizer-1.20.1-1.0.4.zip)
> > > > 
> > > > 
> > > > It sadly did not work: [crash-2024-05-22_04.11.17-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400137/crash-2024-05-22_04.11.17-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400219/latest.log)
> > > > If you think the cause is not from your mod maybe try contacting with the guys from sinytra connector?
> > > 
> > > 
> > > thx, judging by the errors, this version should work [AchievementOptimizer-1.20.1-1.0.4.1.zip](https://github.com/bigenergy/achievement-optimizer/files/15400255/AchievementOptimizer-1.20.1-1.0.4.1.zip)
> > 
> > 
> > Did not work again [crash-2024-05-22_04.21.25-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400296/crash-2024-05-22_04.21.25-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400299/latest.log)
> 
> okay, maybe this version) [AchievementOptimizer-1.20.1-1.0.4.2.zip](https://github.com/bigenergy/achievement-optimizer/files/15400436/AchievementOptimizer-1.20.1-1.0.4.2.zip)

Success!!!!
https://github.com/bigenergy/achievement-optimizer/assets/120287925/0620d50a-77cc-44d2-b0bc-6aef7447aa12

tysm 💃💃💃

**Comment by bigenergy** [comment]
> > > > > > @DeshiDesu pls check new version [AchievementOptimizer-1.20.1-1.0.4.zip](https://github.com/bigenergy/achievement-optimizer/files/15400011/AchievementOptimizer-1.20.1-1.0.4.zip)
> > > > > 
> > > > > 
> > > > > It sadly did not work: [crash-2024-05-22_04.11.17-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400137/crash-2024-05-22_04.11.17-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400219/latest.log)
> > > > > If you think the cause is not from your mod maybe try contacting with the guys from sinytra connector?
> > > > 
> > > > 
> > > > thx, judging by the errors, this version should work [AchievementOptimizer-1.20.1-1.0.4.1.zip](https://github.com/bigenergy/achievement-optimizer/files/15400255/AchievementOptimizer-1.20.1-1.0.4.1.zip)
> > > 
> > > 
> > > Did not work again [crash-2024-05-22_04.21.25-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400296/crash-2024-05-22_04.21.25-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400299/latest.log)
> > 
> > 
> > okay, maybe this version) [AchievementOptimizer-1.20.1-1.0.4.2.zip](https://github.com/bigenergy/achievement-optimizer/files/15400436/AchievementOptimizer-1.20.1-1.0.4.2.zip)
> 
> Success!!!! https://github.com/bigenergy/achievement-optimizer/assets/120287925/0620d50a-77cc-44d2-b0bc-6aef7447aa12
> 
> tysm 💃💃💃

thanks for the tests, this is the final version
[AchievementOptimizer-1.20.1-1.0.5.zip](https://github.com/bigenergy/achievement-optimizer/files/15400606/AchievementOptimizer-1.20.1-1.0.5.zip)

**Comment by DeshiDesu** [comment]
What happened....
[crash-2024-05-22_04.47.08-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400658/crash-2024-05-22_04.47.08-client.txt)
[latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400664/latest.log)

**Comment by bigenergy** [comment]
> What happened.... [crash-2024-05-22_04.47.08-client.txt](https://github.com/bigenergy/achievement-optimizer/files/15400658/crash-2024-05-22_04.47.08-client.txt) [latest.log](https://github.com/bigenergy/achievement-optimizer/files/15400664/latest.log)

I deleted the last change, new version on CF
fixed
